name: Push model to Replicate

# This workflow is triggered manually from the GitHub website.
# To run it, click the "Actions" tab on the repo page.
on:
  workflow_dispatch:
jobs:
  push_to_replicate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        #to save disk space due to large image size
      - name: Cleanup unused docker images
        run: |
          sudo apt autoremove --purge
          sudo apt autoclean
          sudo apt clean
          docker system prune -af
      #to save disk space due to large image size
      - name: CleanUp hostedtoolcache
        run: rm -rf /opt/hostedtoolcache
      #to save disk space due to large image size
      - name: Free disk space
        run: |
          chmod +x ./script/free_disk_space.sh
          ./script/free_disk_space.sh
        shell: bash
      - name: Install Cog
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/download/v0.8.0-beta3/cog_Linux_x86_64
          sudo chmod +x /usr/local/bin/cog
          cog --version
      - name: Log in to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          echo $REPLICATE_API_TOKEN | cog login --token-stdin
      - name: Download model weights
        run: |
          cog run script/download_weights.py
      - name: Push to Replicate
        run: |
          cog push r8.im/flowercomputers/prompt-segmenter
